[package]
name = "extindex"
description = "Persisted immutable index"
version = "0.1.1"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["index", "skip", "list", "persistence"]
repository = "https://github.com/appaquet/extindex-rs"
edition = "2018"

[dependencies]
extsort = "0.2.0"
byteorder = "1.2.7"
log = "0.4.6"
memmap = "0.7"

[dev-dependencies]
tempdir = "0.3"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"
